// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MaterialBarSrc: typeof import('./components/material/bar/src/index.vue')['default']
    MaterialBarSrcConfig: typeof import('./components/material/bar/src/config.vue')['default']
    MaterialLineSrc: typeof import('./components/material/line/src/index.vue')['default']
    UiColorPickerSrc: typeof import('./components/ui/color-picker/src/index.vue')['default']
    UiComIconSrc: typeof import('./components/ui/com-icon/src/index.vue')['default']
    UiFieldCollapseSrc: typeof import('./components/ui/field-collapse/src/index.vue')['default']
    UiFieldSrc: typeof import('./components/ui/field/src/index.vue')['default']
    UiInputNumberSrc: typeof import('./components/ui/input-number/src/index.vue')['default']
    UiInputSrc: typeof import('./components/ui/input/src/index.vue')['default']
    UiInputSrcNewInput: typeof import('./components/ui/input/src/new-input.vue')['default']
    UiLangSelectSrc: typeof import('./components/ui/lang-select/src/index.vue')['default']
    UiLoadingSrc: typeof import('./components/ui/loading/src/index.vue')['default']
    UiLoadingSrcAsyncLoading: typeof import('./components/ui/loading/src/async-loading.vue')['default']
    UiMonacoEditorSrc: typeof import('./components/ui/monaco-editor/src/index.vue')['default']
    UiSelectImageSrc: typeof import('./components/ui/select-image/src/index.vue')['default']
    UiSelectShapeSrc: typeof import('./components/ui/select-shape/src/index.vue')['default']
    UiSelectShapeSrcOptionLabel: typeof import('./components/ui/select-shape/src/option-label.vue')['default']
    UiSelectSrc: typeof import('./components/ui/select/src/index.vue')['default']
    UiSelectSuggestSrc: typeof import('./components/ui/select-suggest/src/index.vue')['default']
    UiSliderSrc: typeof import('./components/ui/slider/src/index.vue')['default']
    UiTooltipPopoverSrc: typeof import('./components/ui/tooltip-popover/src/index.vue')['default']
    UiUploadImageSrc: typeof import('./components/ui/upload-image/src/index.vue')['default']
  }
}

export { }
